### ISSUE TITLE
(Windows) Errors in MonoDevelop 2.8.8.4

### ISSUE THREAD

**Issue by ghost** [jgranick/md-haxebinding#5]
When clicking Haxe option in Tools/Options -> Other/Haxe following error occurs:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeOptionsWidget.Build()
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeOptionsPanel.CreatePanelWidget()
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.CreatePageWidget(SectionPage page)
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.ShowPage(OptionsDialogSection section)
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.OnSelectionChanged(Object s, EventArgs a)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by ghost** [comment]
Forgot to mention ... monodevlop 2.8.8.4 on windows 7 32bit

**Comment by hoseyhosey** [comment]
This doesn't seem to be a consistent issue. My plugin folder requires Mono.Posix.dll V4 as well.  I found it by installing
http://ftp.novell.com/pub/mono/archive/2.10.2/windows-installer/5/mono-2.10.2-gtksharp-2.12.10-win32-5.exe
In there is the mono.posix.dll.  Copy it to the plugin folder.  You can then uninstall the above

**Comment by ghost** [comment]
Update:
Tested on my other machine: win7 64bit ... same errors appear.

Tried about everything that came to mind regarding the matter:
- Installed latest GTK#
- Copied mono.posix.dll in addins folder ( didn't work. After that tried by copying into the win/system32 folder)
- Reinstalled .NET4
- Installed latest mono
- Tested with github .dll and from beta channel

Nothing helped ( no haxe love for me ).

I'll try tomorow on my macbook pro

**Comment by hoseyhosey** [comment]
I ended up putting the mono.posix.dll in the bin folder after installing from addin manager

**Comment by jgranick** [comment]
I'm able to use the add-on properly in Windows using the current alpha version. I think this issue is now resolved
