### ISSUE TITLE
(Windows) Errors in MonoDevelop 2.8.8.4 when completion window is triggered

### ISSUE THREAD

**Issue by ghost** [jgranick/md-haxebinding#6]
When completion window should pop out (manually ctrl+space or automatically during code writing) following error occurs:

Error in text editor extension chain

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeOptionsWidget.Build()
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeOptionsPanel.CreatePanelWidget()
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.CreatePageWidget(SectionPage page)
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.ShowPage(OptionsDialogSection section)
   at MonoDevelop.Ide.Gui.Dialogs.OptionsDialog.OnSelectionChanged(Object s, EventArgs a)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

MonoDevelop 2.8.8.4, win 7 32bit

**Comment by ghost** [comment]
And another one (when manually forcing completion window with ctrl+space)

Error while executing command: Show Completion Window

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.FetchCompletionData(CodeCompletionContext completionContext)
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.GetCompletionList(CodeCompletionContext completionContext)
   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.HandleCodeCompletion(CodeCompletionContext completionContext, Char completionChar)
   at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.CodeCompletionCommand(CodeCompletionContext completionContext)
   at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.RunCompletionCommand()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MonoDevelop.Components.Commands.CommandHandlerInfo.Run(Object cmdTarget, Command cmd)
   at MonoDevelop.Components.Commands.CommandManager.<>c__DisplayClassb.<DispatchCommand>b__2()
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(Object commandId, Object dataItem, Object initialTarget, CommandSource source)

MonoDevelop 2.8.8.4, win 7 32bit

**Comment by jgranick** [comment]
I can't reproduce this on my end. I do get the "Mono.Posix" issue on Windows when trying to access the project or Haxe settings, which both use GTK#... (strange that it can't resolve a path to that core library), however code completion works just fine for me

**Comment by ghost** [comment]
Update: Tried on my macbook pro / snow leaopard

Installed freshly:
- latest haxe
- latest nme
- latest mono / gtk#
- latest monodevelop 2.8.8.4
- installed haxe addon through addon form (not github)

No love for code completion, here the exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.Projects.CodeGeneration.CodeRefactorer.CompleteStatement (MonoDevelop.Projects.Dom.Parser.ProjectDom dom, System.String fileName, DomLocation caretLocation) [0x00007] in /Users/builder/data/lanes/monodevelop-mac-2.8.8.4/cc9fe83c/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.CodeGeneration/CodeRefactorer.cs:315 
  at MonoDevelop.SourceEditor.ExtensibleTextEditor.OnCompleteStatement () [0x00015] in /Users/builder/data/lanes/monodevelop-mac-2.8.8.4/cc9fe83c/source/monodevelop/main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs:971 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at MonoDevelop.Components.Commands.CommandHandlerInfo.Run (System.Object cmdTarget, MonoDevelop.Components.Commands.Command cmd) [0x00029] in /Users/builder/data/lanes/monodevelop-mac-2.8.8.4/cc9fe83c/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:1864 
  at MonoDevelop.Components.Commands.CommandManager+<DispatchCommand>c__AnonStorey42.<>m__57 () [0x0003d] in /Users/builder/data/lanes/monodevelop-mac-2.8.8.4/cc9fe83c/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:1004 
  at MonoDevelop.Components.Commands.CommandManager.DispatchCommand (System.Object commandId, System.Object dataItem, System.Object initialTarget, CommandSource source) [0x0029e] in /Users/builder/data/lanes/monodevelop-mac-2.8.8.4/cc9fe83c/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:1021

**Comment by jgranick** [comment]
I don't think there should be any issues now. I've successfully used the add-in for Windows, Mac and Linux without these issues.

The Mono.Posix error is the only remaining one, which occurs when you try to open Project > Properties or Edit > Preferences > Haxe
