### ISSUE TITLE
Win 7-64 Code Completion

### ISSUE THREAD

**Issue by hoseyhosey** [jgranick/md-haxebinding#8]
Doesnt work for me but new release now throw error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.FetchCompletionData(CodeCompletionContext completionContext)

   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.GetCompletionList(CodeCompletionContext completionContext)

   at MonoDevelop.HaxeBinding.Languages.Gui.HaxeTextEditorCompletion.HandleCodeCompletion(CodeCompletionContext completionContext, Char completionChar)

   at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.CodeCompletionCommand(CodeCompletionContext completionContext)

   at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.RunCompletionCommand()

   --- End of inner exception stack trace ---
at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MonoDevelop.Components.Commands.CommandHandlerInfo.Run(Object cmdTarget, Command cmd)
   at MonoDevelop.Components.Commands.CommandManager.<>c__DisplayClassb.<DispatchCommand>b__2()
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(Object commandId, Object dataItem, Object initialTarget, CommandSource source)

**Comment by jgranick** [comment]
I think this was just resolved in the latest commit. Would you mind updating and seeing if the problem has gone away?

Thanks!
